default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: newpassword
  pool: 5

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
  username: postgres
  password: newpassword
